# RaceSim Performance Requirements
# All units are SI (metric system)
#
# Each metric can have:
#   - target: The ideal target value
#   - min: Minimum acceptable value (for metrics where higher is worse)
#   - max: Maximum acceptable value (for metrics where lower is worse)
#   - weight: Importance weight for overall scoring (0.0 - 1.0)
#   - direction: "lower_better" or "higher_better"

metrics:
  lap_time:
    description: "Total lap time"
    unit: "seconds"
    target: 82.0
    max: 85.0
    weight: 0.25
    direction: lower_better

  fuel_consumption:
    description: "Fuel consumed per lap"
    unit: "kg"
    target: 2.0
    max: 2.5
    weight: 0.15
    direction: lower_better

  max_speed:
    description: "Maximum speed achieved during lap"
    unit: "m/s"
    target: 95.0
    min: 90.0
    weight: 0.15
    direction: higher_better

  avg_speed:
    description: "Average speed during lap"
    unit: "m/s"
    target: 55.0
    min: 50.0
    weight: 0.10
    direction: higher_better

  tire_degradation:
    description: "Tire wear percentage after lap"
    unit: "percent"
    target: 2.0
    max: 4.0
    weight: 0.15
    direction: lower_better

  brake_temp_max:
    description: "Maximum brake temperature reached"
    unit: "celsius"
    target: 400.0
    max: 600.0
    weight: 0.10
    direction: lower_better

  cornering_g_max:
    description: "Maximum lateral G-force in corners"
    unit: "g"
    target: 3.5
    min: 3.0
    weight: 0.05
    direction: higher_better

  energy_recovered:
    description: "Energy recovered through regenerative braking"
    unit: "kJ"
    target: 500.0
    min: 400.0
    weight: 0.05
    direction: higher_better

# Scoring configuration
scoring:
  # How to combine individual metric scores
  method: weighted_average
  
  # Thresholds for pass/fail/warning status
  thresholds:
    excellent: 0.90
    good: 0.75
    acceptable: 0.60
    poor: 0.40

# Time-series threshold definitions for telemetry analysis
# These define crossing events that should be flagged during analysis
telemetry_thresholds:
  # Speed thresholds
  - channel: speed
    name: overspeed_warning
    value: 90.0  # m/s
    direction: above
    severity: warning

  - channel: speed
    name: overspeed_critical
    value: 97.0  # m/s
    direction: above
    severity: critical

  # Tire wear thresholds (per wheel)
  - channel: tire_wear_fl
    name: high_wear_fl
    value: 3.5  # percent
    direction: above
    severity: warning

  - channel: tire_wear_fr
    name: high_wear_fr
    value: 3.5
    direction: above
    severity: warning

  - channel: tire_wear_rl
    name: high_wear_rl
    value: 3.5
    direction: above
    severity: warning

  - channel: tire_wear_rr
    name: high_wear_rr
    value: 3.5
    direction: above
    severity: warning

  - channel: tire_wear_fl
    name: critical_wear_fl
    value: 5.0
    direction: above
    severity: critical

  - channel: tire_wear_fr
    name: critical_wear_fr
    value: 5.0
    direction: above
    severity: critical

  - channel: tire_wear_rl
    name: critical_wear_rl
    value: 5.0
    direction: above
    severity: critical

  - channel: tire_wear_rr
    name: critical_wear_rr
    value: 5.0
    direction: above
    severity: critical

  # Brake temperature thresholds
  - channel: brake_temp_fl
    name: brake_overheat_fl
    value: 550.0  # Celsius
    direction: above
    severity: warning

  - channel: brake_temp_fr
    name: brake_overheat_fr
    value: 550.0
    direction: above
    severity: warning

  - channel: brake_temp_rl
    name: brake_overheat_rl
    value: 550.0
    direction: above
    severity: warning

  - channel: brake_temp_rr
    name: brake_overheat_rr
    value: 550.0
    direction: above
    severity: warning

  - channel: brake_temp_fl
    name: brake_critical_fl
    value: 650.0
    direction: above
    severity: critical

  - channel: brake_temp_fr
    name: brake_critical_fr
    value: 650.0
    direction: above
    severity: critical

  - channel: brake_temp_rl
    name: brake_critical_rl
    value: 650.0
    direction: above
    severity: critical

  - channel: brake_temp_rr
    name: brake_critical_rr
    value: 650.0
    direction: above
    severity: critical

  # G-force thresholds
  - channel: g_lateral
    name: high_lateral_g
    value: 3.5  # g
    direction: above
    severity: info

  - channel: g_lateral
    name: extreme_lateral_g
    value: 4.5
    direction: above
    severity: warning

  - channel: g_longitudinal
    name: heavy_braking
    value: -4.0  # negative = braking
    direction: below
    severity: info

  # Fuel thresholds
  - channel: fuel_remaining
    name: low_fuel_warning
    value: 1.0  # kg
    direction: below
    severity: warning

  - channel: fuel_remaining
    name: critical_fuel
    value: 0.3
    direction: below
    severity: critical
